;;; Compiled snippets and support files for `nxml-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'nxml-mode
                     '(("xml" "<?xml version=\"1.0\" encoding=\"utf-8\"?>$0" "xml template" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/xml.yasnippet" nil nil)
                       ("uses" "<uses-permission android:name=\"android.permission.$0\" />" "Permission Template" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/uses_permission.yasnippet" nil nil)
                       ("tv" "<TextView\n    xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    android:id=\"@+id/$1\"\n    android:layout_width=\"wrap_content\"\n    android:layout_height=\"wrap_content\"\n    android:minHeight=\"?android:attr/listPreferredItemHeight\"\n    android:gravity=\"center_vertical\"\n    android:text=\"@string/$2\" />$0" "Template for Android TextView" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/textview.yasnippet" nil nil)
                       ("scrollview" "<ScrollView\n    android:id=\"@+id/$1\"\n    android:layout_width=\"match_parent\"\n    android:layout_height=\"wrap_content\">\n    $0\n</ScrollView>" "Template for ScrollView" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/scroll_view.yasnippet" nil nil)
                       ("preferencescreen" "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<PreferenceScreen\n    xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    android:layout_width=\"match_parent\"\n    android:layout_height=\"match_parent\">\n\n    $0\n\n</PreferenceScreen>\n" "Template for Preference Screen" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/preference_screen.yasnippet" nil nil)
                       ("name" "<string name=\"$1\">$0</string>" "Name String" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/name.yasnippet" nil nil)
                       ("menu" "<menu\n    xmlns:android=\"http://schemas.android.com/apk/res/android\"\n    xmlns:app=\"http://schemas.android.com/apk/res-auto\">\n    <item\n        android:id=\"@+id/action_$1\"\n        android:title=\"@string/action_$2\"\n        android:showAsAction=\"${3:never}\" />\n</menu>$0" "Menu template" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/menu.yasnippet" nil nil)
                       ("listview" "<ListView\n        android:id=\"@+id/$1\"\n        android:layout_width=\"match_parent\"\n        android:layout_height=\"match_parent\" />$0" "Template for ListView" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/list_view.yasnippet" nil nil)
                       ("listpreference" "<ListPreference\n     android:title=\"@string/pref_$1\"\n     android:key=\"@string/pref_$2_key\"\n     android:defaultValue=\"@string/pref_$3\"\n     android:entryValues=\"@array/pref_$4\"\n     android:entries=\"@array/pref_$5\" />$0" "List Preference" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/list_preference.yasnippet" nil nil)
                       ("item" "<item android:id=\"@+id/action_$1\"\n    android:title=\"@string/action_$2\"\n    android:showAsAction=\"${3:never}\" />$0" "Item template" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/item.yasnippet" nil nil)
                       ("id" "android:id=\"@+id/$1\"$0" "Id template for widget" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/id.yasnippet" nil nil)
                       ("edittextpreference" "<EditTextPreference\n    android:title=\"@string/pref_$1\"\n    android:key=\"@string/pref_$2\"\n    android:defaultValue=\"@string/pref_$3\"\n    android:inputType=\"${4:text}\"\n    android:singleLine=\"${5:true}\" />$0" "Edit text preference" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/edittext.yasnippet" nil nil)
                       ("edittext" "<EditText\n    android:id=\"@+id/$1\"\n    android:layout_width=\"fill_parent\"\n    android:layout_height=\"wrap_content\"\n    android:hint=\"@string/$2\"\n    android:inputType=\"${3:text}\" />$0" "Template for Edit Text" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/edit_text.yasnippet" nil nil)
                       ("btn" "<Button\n      android:id=\"@+id/$1\"\n      android:layout_width=\"wrap_content\"\n      android:layout_height=\"wrap_content\"\n      android:text=\"@string/$2\" />$0" "Template for Android Button" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/button.yasnippet" nil nil)
                       ("a" "android:$0" "android" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/android.yasnippet" nil nil)
                       ("activity" "<activity\n    android:name=\".$1\"\n    android:label=\"@string/title_activity_$2\"\n    android:parentActivityName=\".MainActivity\" >\n    <meta-data\n        android:name=\"android.support.PARENT_ACTIVITY\"\n        android:value=\"$3.MainActivity\" />\n</activity>$0" "Activity Template for Manifest file" nil nil nil "/Users/gopar/.emacs.d/mysnippets/nxml-mode/activity.yasnippet" nil nil)))


;;; Do not edit! File generated at Fri Jan  5 17:58:00 2018
